"""System Information page: architecture, active configuration, known
limitations, and the research disclaimer."""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import streamlit as st

from config.settings import APP_NAME, APPLICATION_CONFIG
from database.database import get_session, init_db
from src.utils.auth_ui import require_login
from database.models import Dataset, ModelVersion
from database.repositories.user_repository import UserRepository
from src.services.auth_service import create_user
from src.utils.streamlit_helpers import clear_all_caches

st.set_page_config(page_title=f"System Information - {APP_NAME}", layout="wide")
init_db()
require_login()

st.title("System Information")

st.info(
    "This application is a research predictive-maintenance decision-support "
    "prototype. Predictions are probabilistic estimates generated by "
    "machine-learning models and must be interpreted together with "
    "engineering inspection, operating procedures, and qualified "
    "maintenance judgment.",
    icon="ℹ️",
)

st.subheader("Architecture")
st.code(
    """
Excel/CSV (Data Repo)
  -> Ingestion (ExcelDataSource / CSVDataSource)
  -> Column Mapping (src.ingestion.mapper)
  -> Standardized Schema
  -> Preprocessing (cleaning, missing values, outliers)
  -> Dataset Feasibility Report
  -> Feature Engineering (raw + temporal groups; label-formula columns excluded)
  -> Intervention-Priority Label Construction (thresholds fit on train split only)
  -> Model Training (Logistic Regression, Decision Tree, Random Forest, XGBoost)
  -> Model Selection (PR-AUC primary, recall tie-break)
  -> Inference Engine -> Priority Engine -> SHAP Explainability
  -> Alert Engine -> SQLite Database
  -> Streamlit Decision-Support Interface / Power BI Export
    """,
    language="text",
)

st.subheader("Primary ML Task")
st.markdown(
    f"**{APPLICATION_CONFIG['prediction']['task_type']}** -- CMMS-based "
    "intervention-priority classification. The connected dataset (a real "
    "Limble CMMS export) has no continuous sensor telemetry and no populated "
    "failure/breakdown log, so the task was reframed from time-horizon "
    "failure prediction to classifying each asset's current intervention "
    "priority from its profile and PM/work-order compliance activity."
)

st.subheader("Active Configuration")
with get_session() as session:
    datasets = session.query(Dataset).all()
    active_model = session.query(ModelVersion).filter_by(active=True).first()

col1, col2 = st.columns(2)
col1.metric("Datasets Imported", len(datasets))
col2.metric(
    "Active Model",
    f"{active_model.model_type} v{active_model.version}" if active_model else "None",
)

st.subheader("Accounts")
st.caption(
    "Everyone signed in has the same access -- there's no separate "
    "admin-only mode. Add an account for anyone else (an MML colleague, "
    "your supervisor) who should be able to sign in."
)
with get_session() as session:
    users = UserRepository(session).list()
    user_rows = [
        {
            "display_name": u.display_name,
            "username": u.username,
            "role": u.role,
            "last_login_at": u.last_login_at,
        }
        for u in users
    ]
st.dataframe(user_rows, use_container_width=True, hide_index=True)

with st.expander("Add an account"):
    with st.form("add_user_form", clear_on_submit=True):
        new_display_name = st.text_input("Name", key="new_user_display_name")
        new_username = st.text_input("Username", key="new_user_username")
        new_password = st.text_input("Temporary password", type="password", key="new_user_password")
        new_role = st.selectbox("Role label (informational only)", ["Member", "Admin"], key="new_user_role")
        add_submitted = st.form_submit_button("Add account")

    if add_submitted:
        with get_session() as session:
            result = create_user(session, new_username, new_display_name, new_password, role=new_role)
        if not result.ok:
            st.error(result.error)
        else:
            st.success(
                f"Account created for {result.user.display_name} (@{result.user.username}). "
                "Share the temporary password with them directly -- there's no email "
                "invite flow, so they should sign in and you should tell them to keep "
                "it somewhere safe."
            )
            st.rerun()

st.subheader("Application Cache")
st.caption(
    "The app caches dataset lists, processed datasets, and the active "
    "model in memory so navigating between pages feels fast. This is "
    "cleared automatically after importing, deleting, or training a "
    "dataset -- use this if you ever suspect a page is showing stale "
    "data (e.g. after editing files directly on disk), or just to free "
    "memory."
)
if st.button("Clear Cache"):
    clear_all_caches()
    st.success("Cache cleared.")

st.subheader("Known Limitations")
st.markdown(
    """
- Equipment category/manufacturer/criticality fields are sparsely populated
  in the source CMMS export (see the Dataset Feasibility page) -- the model
  relies most heavily on PM completion counts and recency.
- An LSTM/GRU sequence model is implemented (`src/training/sequence_model.py`)
  and was trained and evaluated against a separate, clearly-labeled
  synthetic sensor dataset (see `docs/synthetic_demo_track.md`), since the
  real CMMS data is a single point-in-time snapshot per machine with no
  per-machine time series to model. It has not been run against the real
  MML data for this reason, and no thesis conclusion about MML's actual
  equipment cites numbers from that synthetic track.
- The intervention-priority label is derived from real compliance metrics
  (overdue PMs/WOs, downtime), not an observed ground-truth failure event --
  it is a defensible proxy target, not a verified failure history.
- Real-time (IoT/SCADA/API) integration is architected for but not
  implemented -- see `docs/real_time_scaling.md`.
    """
)
